### ISSUE TITLE
Using name volume in docker-compose error

### ISSUE THREAD

**Issue by igreenfield** [EnterpriseDB/docker-postgresql#89]
```
version: '3.9'
services:
  entpg13:
    image: ghcr.io/enterprisedb/postgresql:13.6-debian
    ports:
      - 5433:5432
    volumes:
      - ePgdataVol:/data
    environment:
      POSTGRES_DB: dbname
      POSTGRES_PASSWORD: dbadmin
      POSTGRES_USER: dbadmin
      PGDATA: /data
volumes:
  ePgdataVol:
    external: true
```
leads to:

chmod: changing permissions of '/data': Operation not permitted
2022-03-15T17:53:53.974807400Z The files belonging to this database system will be owned by user "postgres".
2022-03-15T17:53:53.974820400Z This user must also own the server process.
2022-03-15T17:53:53.974822400Z 
2022-03-15T17:53:53.974823800Z The database cluster will be initialized with locale "en_US.utf8".
2022-03-15T17:53:53.974825200Z The default database encoding has accordingly been set to "UTF8".
2022-03-15T17:53:53.974826700Z The default text search configuration will be set to "english".
2022-03-15T17:53:53.974828200Z 
2022-03-15T17:53:53.974829500Z Data page checksums are disabled.
2022-03-15T17:53:53.974965700Z 
2022-03-15T17:53:53.974978200Z initdb: error: could not change permissions of directory "/data": Operation not permitted
2022-03-15T17:53:53.984269500Z fixing permissions on existing directory /data ...
